export {Databox} from './databox';
export {Obj} from './obj';
export {PeopleInfo} from './people-info';
export {ServiceResult} from './service-result';
export {StudentListRes} from './student-list-res';
export {TeacherListRes} from './teacher-list-res';
export {DistrictInfo} from './district-info';
export {DistrictListRes} from './district-list-res';
export {SelectData} from './select-data';